#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Corpus M1 for the AIxCC nginx challenge: turn the 14 CPVs into case.yaml
# files, and prove each one round-trips before writing it.
#
# Round-tripping is the whole point. For every case this builds the target
# twice: once at the pin, where the proof of vulnerability must fire the
# sanitizer the challenge declares, and once with the reference patch applied,
# where it must go quiet. Neither half means anything alone. A case that only
# fires proves the blob crashes something; a case that only goes quiet proves
# the build is broken. The pair is what establishes that this blob, this
# harness and this patch describe the same vulnerability.
#
# A case that does not round-trip is not written out. It is reported and the
# run fails, because a corpus entry the gate cannot trust would grade every
# later stage against a fiction.
set -euo pipefail

CP="${CP:-/var/tmp/arazu-nginx/cp}"
SHIM="${SHIM:-/mnt/4TB1/arazu-corpus/shim}"
CASES="${CASES:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/cases/nginx}"

export PATH="$SHIM:$PATH"
export DOCKER_USER_ARGS="-e LOCAL_USER=0:0"

cd "$CP"
mkdir -p "$CASES"

if [ -z "${DOCKER_IMAGE_NAME:-}" ]; then
    base=$(yq -r '.docker_image' project.yaml)
    DOCKER_IMAGE_NAME=$(docker images --format '{{.Repository}}:{{.Tag}}' |
                        grep "^${base}:" | grep -v ':<none>$' | head -1)
    export DOCKER_IMAGE_NAME
fi

CP_COMMIT=$(git rev-parse HEAD)
SRC_REF=$(yq -r '.cp_sources.nginx.ref' project.yaml)
SRC_COMMIT=$(git -C src/nginx rev-parse "$SRC_REF^{commit}")
SANITIZERS=$(yq -r '.sanitizers[]' project.yaml)

latest_pov_dir() {
    find "$CP/out/output" -maxdepth 1 -name '*--run_pov' -printf '%T@ %p\n' 2>/dev/null |
        sort -rn | head -1 | cut -d' ' -f2-
}

# Which declared sanitizer string, if any, appears in the last PoV run.
fired() {
    local d; d=$(latest_pov_dir)
    while IFS= read -r s; do
        if grep -qF "$s" "$d/stderr.log" 2>/dev/null; then printf '%s' "$s"; return; fi
    done <<< "$SANITIZERS"
    printf 'none'
}

# The frame ASan blames, which is what a human reads first in the dossier.
crash_site() {
    local d; d=$(latest_pov_dir)
    grep -m1 -oE '#[0-9]+ 0x[0-9a-f]+ in [A-Za-z_][A-Za-z0-9_]* [^ ]+' "$d/stderr.log" 2>/dev/null |
        sed -E 's/^#[0-9]+ 0x[0-9a-f]+ in //' || true
}

reset_src() { git -C src/nginx reset --hard "$SRC_COMMIT" -q; git -C src/nginx clean -fdxq; }

fail=0
written=0
for dir in "$CP"/.internal_only/cpv*/; do
    id=$(basename "$dir")
    harness=$(sed 's/,.*//' "$dir/pov_pou_info")
    expected=$(sed 's/^[^,]*, *//' "$dir/pov_pou_info")
    blob=$(find "$dir/blobs" -type f | head -1)
    good="$dir/patches/nginx/good_patch.diff"
    # Descriptive only, and the files are not consistent about it: cpv9 writes
    # "[CWE-416](...)Use-After-Free<br>" with no space after the bracket. Under
    # pipefail a grep that matches nothing kills the whole run, so a cosmetic
    # field is not allowed to decide whether the corpus gets built.
    cwe=$(grep -oE 'CWE-[0-9]+' "$dir/CPVINFO.md" | head -1 || true)
    cwe_name=$(grep -oE '\)[[:space:]]*[A-Za-z][A-Za-z -]+' "$dir/CPVINFO.md" |
               head -1 | sed 's/^)[[:space:]]*//;s/[[:space:]]*$//;s/<br>$//' || true)

    echo "== $id =="

    # Arm one: at the pin, the vulnerability must be present.
    reset_src
    ./run.sh build >/dev/null 2>&1
    ./run.sh run_pov "$blob" "$harness" >/dev/null 2>&1 || true
    unpatched=$(fired)
    site=$(crash_site)

    # Arm two: with the reference patch, the same blob must stop firing.
    reset_src
    ./run.sh build "$good" nginx >/dev/null 2>&1
    ./run.sh run_pov "$blob" "$harness" >/dev/null 2>&1 || true
    patched=$(fired)

    if [ "$unpatched" != "$expected" ] || [ "$patched" != "none" ]; then
        printf '   FAIL unpatched=%s (want %s), patched=%s (want none)\n' \
            "$unpatched" "$expected" "$patched"
        fail=1
        continue
    fi
    printf '   ok   fires %s unpatched, silent under the reference patch\n' "$expected"

    rel_blob=${blob#"$CP"/}
    rel_blob=${rel_blob//\/\//\/}
    cat > "$CASES/$id.yaml" <<YAML
# Generated by corpus/normalise-nginx.sh. Every field below was established by
# running the case, not by reading the challenge's own labels.
id: nginx-$id
language: c
cwe: $cwe
cwe_name: $cwe_name
target: nginx
harness: $harness

source:
  cp_repo: https://github.com/aixcc-public/challenge-004-nginx-cp.git
  cp_commit: $CP_COMMIT
  src_repo: https://github.com/aixcc-public/challenge-004-nginx-source.git
  src_ref: $SRC_REF
  src_commit: $SRC_COMMIT

pov:
  input: $rel_blob
  expected_sanitizer: "$expected"
  crash_location: "$site"
  # The container exits 0 whether or not the vulnerability fires, so the
  # sanitizer string in stderr.log is the only signal. A gate keyed on the
  # exit code would accept every candidate patch.
  signal: stderr.log

reference_patch: .internal_only/$id/patches/nginx/good_patch.diff

candidates:
  - id: $id-aixcc-bad
    patch: .internal_only/$id/patches/nginx/bad_patch.diff
    label: unclassified
    # Shipped by the challenge as a deliberately wrong fix. The class it
    # belongs to, and so the reason the gate should give, is established by
    # corpus/classify-nginx.sh rather than assumed here.
    expected_gate_reason: null
YAML
    written=$((written + 1))
done

reset_src
echo
echo "wrote $written case files to $CASES"
[ $fail -eq 0 ] || { echo "at least one case did not round-trip" >&2; exit 1; }
echo "every case round-trips: fires at the pin, silent under its reference patch"
