#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Read one Shellphish artiphishell run into the layout cmd/drive already expects.
#
# WHY A SCRIPT AND NOT A COMPONENT. artiphishell is a 54-component pydatatask
# pipeline; adding a stage to it would put Arazu inside the thing it is judging,
# which is the one arrangement the seam exists to prevent. `pd backup` copies
# repository contents to a folder, so the whole bridge is an export and a
# rename. Nothing is installed into artiphishell and it never learns Arazu ran.
#
# WHAT IT PRODUCES. The same shape pkg/crsout.Capture reads for Buttercup:
#
#   <out>/run/<task-id>/patches/<patch-id>.patch
#   <out>/run/<task-id>/povs/<pov-id>.bin
#   <out>/seed-case.yaml
#
# cmd/drive then does the rest. The seed case exists only to carry source
# metadata (repo, commits, harness, sanitizer), because artifacts cannot supply
# it and crsout.sourceOf reads it from a case. It is NOT an oracle: it carries
# no reference_patch and no expected_gate_reason, and Capture writes the real
# captured case itself.
#
# The repository names below are artiphishell's, read from
# components/patch-validation-testing/pipeline.yaml. If that file renames one,
# this fails loudly on the missing directory rather than silently exporting less.
set -uo pipefail

PIPELINE="${ARTIPHISHELL_DIR:-}"
OUT="${OUT:-}"
TASK="${TASK:-}"

usage() {
    cat >&2 <<'EOF'
usage: adapt-artiphishell.sh -p <artiphishell-checkout> -o <out-dir> [-t <task-id>]

  -p  artiphishell working copy, where `pd` can resolve pipeline.yaml
  -o  directory to write run/ and seed-case.yaml into
  -t  task id to capture; default is the newest patch's task

Source metadata must be supplied, since no artiphishell repository carries it:
  ARAZU_SRC_REPO, ARAZU_SRC_COMMIT, ARAZU_BASE_COMMIT,
  ARAZU_PROJECT, ARAZU_HARNESS, ARAZU_SANITIZER
Optional, and worth setting because M3 loses the site comparison without them:
  ARAZU_EXPECTED_SANITIZER, ARAZU_CRASH_LOCATION
EOF
    exit 2
}

while getopts 'p:o:t:' opt; do
    case "$opt" in
        p) PIPELINE=$OPTARG ;;
        o) OUT=$OPTARG ;;
        t) TASK=$OPTARG ;;
        *) usage ;;
    esac
done
[ -n "$PIPELINE" ] && [ -n "$OUT" ] || usage
[ -d "$PIPELINE" ] || { echo "no artiphishell checkout at $PIPELINE" >&2; exit 2; }
command -v pd >/dev/null || { echo "pd (pydatatask) not on PATH; pip install -e $PIPELINE/libs/pydatatask" >&2; exit 2; }

# Fail on unset source metadata rather than writing a case with empty commits.
# An empty src_commit produces a case that loads and then grades nothing, which
# reads as the gate being broken instead of the capture being incomplete.
for v in ARAZU_SRC_REPO ARAZU_SRC_COMMIT ARAZU_BASE_COMMIT ARAZU_PROJECT ARAZU_HARNESS ARAZU_SANITIZER; do
    [ -n "${!v:-}" ] || { echo "$v is unset; see -h. Source metadata is not in any artiphishell repository." >&2; exit 2; }
done

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Read-only export. These five are the repositories that hold Arazu's three
# inputs plus their provenance; nothing is written back into the pipeline.
REPOS=(
    patch_diffs
    patch_metadatas
    pov_report_representative_crashing_inputs
    pov_report_representative_crashing_input_metadatas
    targets_with_sources
)
( cd "$PIPELINE" && pd backup "$STAGE" "${REPOS[@]}" ) >/dev/null 2>&1 || {
    echo "pd backup failed in $PIPELINE; run it by hand to see why" >&2
    exit 1
}

[ -d "$STAGE/patch_diffs" ] || { echo "no patch_diffs in the export: the run produced no patch" >&2; exit 1; }

# pd backup lays each repository out as <repo>/<job-id>, where the job id is
# artiphishell's patch id. The newest one is the default because a live pipeline
# keeps producing them and capturing a stale patch silently grades the wrong
# thing.
if [ -z "$TASK" ]; then
    TASK=$(ls -t "$STAGE/patch_diffs" 2>/dev/null | head -1)
fi
[ -n "$TASK" ] || { echo "no patch to capture" >&2; exit 1; }
[ -s "$STAGE/patch_diffs/$TASK" ] || { echo "no patch_diffs entry for $TASK" >&2; exit 1; }

RUN="$OUT/run/$TASK"
mkdir -p "$RUN/patches" "$RUN/povs"
cp "$STAGE/patch_diffs/$TASK" "$RUN/patches/$TASK.patch"

# The PoV is keyed independently of the patch, so take every representative
# crashing input rather than guessing which one this patch answers. crsout picks
# one and records how many it saw.
n=0
if [ -d "$STAGE/pov_report_representative_crashing_inputs" ]; then
    for p in "$STAGE/pov_report_representative_crashing_inputs"/*; do
        [ -s "$p" ] || continue
        cp "$p" "$RUN/povs/$(basename "$p").bin"
        n=$((n + 1))
    done
fi
[ "$n" -gt 0 ] || {
    echo "a patch exists with no representative crashing input; no stage that runs a PoV can attribute it" >&2
    exit 1
}

CASE="$OUT/seed-case.yaml"
cat > "$CASE" <<EOF
# Generated by scripts/adapt-artiphishell.sh. Not an oracle: this exists only to
# carry source metadata into crsout.sourceOf, which cannot read it from any
# artiphishell repository. It deliberately has no reference_patch and no
# expected_gate_reason, so M2 declines rather than grading against a fix nobody
# has. cmd/drive writes the real captured case.
kind: captured
id: artiphishell-$TASK
language: c
root: repo
target: $ARAZU_PROJECT
harness: $ARAZU_HARNESS

source:
  cp_repo: "$ARAZU_SRC_REPO"
  cp_commit: "$ARAZU_SRC_COMMIT"
  src_repo: "$ARAZU_SRC_REPO"
  src_ref: "$ARAZU_SRC_COMMIT"
  src_commit: "$ARAZU_SRC_COMMIT"
  base_commit: "$ARAZU_BASE_COMMIT"
  fuzz_tooling_project: $ARAZU_PROJECT

pov:
  input: povs/$(ls "$RUN/povs" | head -1)
  sanitizer: $ARAZU_SANITIZER
  expected_sanitizer: "${ARAZU_EXPECTED_SANITIZER:-}"
  crash_location: "${ARAZU_CRASH_LOCATION:-}"
  signal: stderr

candidates:
  - id: artiphishell-$TASK-candidate
    patch: patches/$TASK.patch
    label: unclassified
EOF

printf '%s\n' "{\"adapter\":\"artiphishell\",\"task\":\"$TASK\",\"patches\":1,\"povs\":$n,\"run\":\"$OUT/run\",\"case\":\"$CASE\"}"
echo "next: ./bin/drive -run $OUT/run -task $TASK -case $CASE -out $OUT/captured -stage m1" >&2
