#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Read one 42-b3yond-6ug (BugBuster) run into the layout cmd/drive expects.
#
# WHY THIS ONE IS A QUERY AND NOT AN EXPORT. BugBuster keeps its state in
# PostgreSQL rather than on disk, so there is no run directory to point at. The
# schema is declared in components/patchagent/aixcc/db.py and is stable enough to
# read directly, which is less brittle than parsing anyone's directory layout.
#
# THE ONE THING THAT SURPRISED ME, and the reason this is not a pure query:
# patches.patch holds the diff as TEXT, but bugs.poc holds a PATH, not bytes.
# components/submitter/submission.py does `open(content.poc, "rb").read()`, so
# the reproducer is a file on the box that ran the CRS. This script copies it.
# If you are running against a database from another host, the poc paths will not
# resolve and it says so rather than writing an empty PoV.
#
# WHAT IT PRODUCES. The same shape pkg/crsout.Capture reads for Buttercup:
#
#   <out>/run/<patch-id>/patches/<patch-id>.patch
#   <out>/run/<patch-id>/povs/<bug-id>.bin
#   <out>/seed-case.yaml
#
# Unlike artiphishell, most source metadata IS available here: bug_profiles
# carries harness_name, sanitizer, sanitizer_bug_type and trigger_point. Only the
# repository and commits have to be supplied.
set -uo pipefail

OUT="${OUT:-}"
PATCH_ID="${PATCH_ID:-}"
DSN="${ARAZU_42B_DSN:-}"

usage() {
    cat >&2 <<'EOF'
usage: adapt-42b.sh -d <postgres-dsn> -o <out-dir> [-i <patch-id>]

  -d  libpq DSN for BugBuster's database, or set ARAZU_42B_DSN
  -o  directory to write run/ and seed-case.yaml into
  -i  patches.id to capture; default is the newest patch

Supplied by the query (bug_profiles): harness, sanitizer, bug type, trigger point
Must be supplied, since BugBuster records the task but not the source coordinates:
  ARAZU_SRC_REPO, ARAZU_SRC_COMMIT, ARAZU_BASE_COMMIT, ARAZU_PROJECT
EOF
    exit 2
}

while getopts 'd:o:i:' opt; do
    case "$opt" in
        d) DSN=$OPTARG ;;
        o) OUT=$OPTARG ;;
        i) PATCH_ID=$OPTARG ;;
        *) usage ;;
    esac
done
[ -n "$DSN" ] && [ -n "$OUT" ] || usage
command -v psql >/dev/null || { echo "psql required" >&2; exit 2; }

for v in ARAZU_SRC_REPO ARAZU_SRC_COMMIT ARAZU_BASE_COMMIT ARAZU_PROJECT; do
    [ -n "${!v:-}" ] || { echo "$v is unset; see -h" >&2; exit 2; }
done

q() { psql "$DSN" -At -F $'\t' -c "$1" 2>/dev/null; }

# One row per patch: the diff, and the bug profile it answers. bug_groups is the
# join from a profile to the concrete bugs under it, and bugs.poc is the path.
#
# NOTE ON WHAT IS DELIBERATELY NOT FILTERED. The obvious query would restrict to
# patches BugBuster considered valid, which is
# `patch_status.functionality_tests_passing IS DISTINCT FROM false`. That is the
# condition in patch_submitter/main.py, and it counts a NULL — never measured —
# as valid. Filtering on it here would hide exactly the patches Arazu exists to
# adjudicate, so this takes them all and records what BugBuster thought.
if [ -z "$PATCH_ID" ]; then
    PATCH_ID=$(q "SELECT id FROM patches ORDER BY created_at DESC LIMIT 1")
fi
[ -n "$PATCH_ID" ] || { echo "no patches in the database" >&2; exit 1; }

row=$(q "
  SELECT p.patch,
         bp.harness_name,
         bp.sanitizer,
         bp.sanitizer_bug_type,
         bp.trigger_point,
         COALESCE((SELECT string_agg(DISTINCT b.poc, '|')
                     FROM bug_groups bg JOIN bugs b ON b.id = bg.bug_id
                    WHERE bg.bug_profile_id = bp.id), ''),
         COALESCE((SELECT ps.functionality_tests_passing::text
                     FROM patch_status ps WHERE ps.patch_id = p.id
                    ORDER BY ps.id DESC LIMIT 1), 'never-measured')
    FROM patches p JOIN bug_profiles bp ON bp.id = p.bug_profile_id
   WHERE p.id = $PATCH_ID")
[ -n "$row" ] || { echo "no patch $PATCH_ID, or it has no bug profile" >&2; exit 1; }

IFS=$'\t' read -r diff harness sanitizer bugtype trigger pocs funcstatus <<<"$row"
[ -n "$diff" ] || { echo "patch $PATCH_ID has an empty diff" >&2; exit 1; }

RUN="$OUT/run/$PATCH_ID"
mkdir -p "$RUN/patches" "$RUN/povs"
printf '%s\n' "$diff" > "$RUN/patches/$PATCH_ID.patch"

n=0; missing=0
IFS='|' read -ra plist <<<"$pocs"
for p in "${plist[@]}"; do
    [ -n "$p" ] || continue
    if [ -r "$p" ]; then
        cp "$p" "$RUN/povs/$(basename "${p%.*}")-$n.bin"
        n=$((n + 1))
    else
        missing=$((missing + 1))
    fi
done
[ "$n" -gt 0 ] || {
    echo "patch $PATCH_ID has $missing poc path(s) and none is readable here." >&2
    echo "bugs.poc is a path on the host that ran BugBuster, not bytes in the database." >&2
    exit 1
}

CASE="$OUT/seed-case.yaml"
cat > "$CASE" <<EOF
# Generated by scripts/adapt-42b.sh. Not an oracle: it carries source metadata
# into crsout.sourceOf and nothing more. No reference_patch and no
# expected_gate_reason, so M2 declines rather than grading against a fix nobody
# has. cmd/drive writes the real captured case.
#
# BugBuster's own view of this patch was functionality_tests_passing=$funcstatus.
# Recorded, not acted on: never-measured is the state its submitter counts as
# passing, and re-deciding it is the whole point of running the gate.
kind: captured
id: bugbuster-$PATCH_ID
language: c
root: repo
target: $ARAZU_PROJECT
harness: $harness

source:
  cp_repo: "$ARAZU_SRC_REPO"
  cp_commit: "$ARAZU_SRC_COMMIT"
  src_repo: "$ARAZU_SRC_REPO"
  src_ref: "$ARAZU_SRC_COMMIT"
  src_commit: "$ARAZU_SRC_COMMIT"
  base_commit: "$ARAZU_BASE_COMMIT"
  fuzz_tooling_project: $ARAZU_PROJECT

pov:
  input: povs/$(ls "$RUN/povs" | head -1)
  sanitizer: $sanitizer
  expected_sanitizer: "$bugtype"
  crash_location: "$trigger"
  signal: stderr

candidates:
  - id: bugbuster-$PATCH_ID-candidate
    patch: patches/$PATCH_ID.patch
    label: unclassified
EOF

printf '%s\n' "{\"adapter\":\"42b\",\"patch_id\":\"$PATCH_ID\",\"povs\":$n,\"poc_paths_unreadable\":$missing,\"crs_functionality_tests\":\"$funcstatus\",\"run\":\"$OUT/run\",\"case\":\"$CASE\"}"
echo "next: ./bin/drive -run $OUT/run -task $PATCH_ID -case $CASE -out $OUT/captured -stage m1" >&2
