#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Stand up a LiteLLM proxy that can only reach ollama, for driving a CRS locally.
#
# WHY IT ONLY ROUTES TO OLLAMA, AND WHY THAT IS THE POINT. A CRS asks for models
# by name — artiphishell alone names 53 of them, from gpt-3.5-turbo to
# claude-4-opus — and picks one at runtime. If the proxy carries even one real
# upstream, a component that asks for the wrong name spends money, and a fuzzing
# campaign asks a great many times. Buttercup's own run was 149 calls for one
# bug. So this config declares NO anthropic, openai, azure or gemini upstream at
# all: every name it knows resolves to ollama, and a name it does not know is a
# 400 rather than a bill. Fail closed, in the same sense the gate does.
#
# The corollary is that this is for the DISCOVERY half. Judging with a frontier
# model is a separate, metered thing: corpus/judge-arm.sh talks to Anthropic
# directly and is one call per candidate, which is a cost you can count.
#
# A reasoning local model (gpt-oss:20b) spends max_tokens on reasoning_content
# BEFORE it writes any content, so a small budget returns an empty string and
# reads as a broken proxy. The check below asks for 256 for that reason. If a
# CRS component sets its own small max_tokens it will see the same emptiness:
# prefer a non-reasoning local model (devstral:24b, qwen3-coder:30b) if that
# starts happening rather than trying to raise budgets inside the CRS.
#
# Chat names all resolve to one local model because the point is to exercise the
# CRS's plumbing, not to compare models. Embeddings need their own, since a chat
# model returns none and the component that asked gets an error that reads like
# a proxy fault.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PORT="${ARAZU_LITELLM_PORT:-4000}"
OLLAMA="${ARAZU_OLLAMA_URL:-http://127.0.0.1:11434}"
CHAT="${ARAZU_LOCAL_MODEL:-gpt-oss:20b}"
EMBED="${ARAZU_LOCAL_EMBED:-nomic-embed-text}"
# artiphishell's local_run/env.sh default, so nothing has to be overridden there.
KEY="${LITELLM_KEY:-sk-artiphishell-da-best!!!}"
NAME="${ARAZU_LITELLM_NAME:-arazu-litellm}"
CONF="${ARAZU_LITELLM_CONF:-$HERE/../state/litellm-local.yaml}"

usage() { echo "usage: $0 <write|up|down|check|models>" >&2; exit 2; }
[ $# -ge 1 ] || usage

# Every name artiphishell can ask for, from
#   grep -rhoE '"(claude|gpt|o1|o3|o4|gemini|text-embedding)[a-zA-Z0-9._-]*"'
# over libs/ and components/. Buttercup's set is a subset. Adding a name costs
# nothing; a missing one costs a confusing runtime failure deep in a component.
CHAT_NAMES=(
  claude claude-3 claude-3.5-haiku claude-3-5-sonnet claude-3.5-sonnet
  claude-3-5-sonnet-20241022 claude-3-7-sonnet claude-3.7-sonnet
  claude-3-7-sonnet-20250219 claude-3-haiku claude-3-haiku-20240307
  claude-3-opus claude-3-sonnet claude-3-sonnet-20240229 claude-4-opus
  claude-4-sonnet claude-opus-4 claude-sonnet-4
  gemini gemini-1.5-flash gemini-1.5-flash-8b gemini-1.5-pro gemini-2.0-flash
  gemini-2.0-flash-lite gemini-2.5-pro gemini-2.5-pro-preview
  gpt gpt-3-5-turbo gpt-3.5-turbo gpt-3.5-turbo-1106 gpt-4 gpt-4.1
  gpt-4.1-mini gpt-4.1-nano gpt-4.5-turbo gpt-4o gpt-4o-mini gpt-4-turbo
  gpt-o3 gpt-o4-mini o1 o1-mini o1-preview o3 o3-mini o4 o4-mini
)
EMBED_NAMES=( text-embedding-ada-002 text-embedding-3-small text-embedding-3-large )

write_conf() {
    mkdir -p "$(dirname "$CONF")"
    {
        echo "# Generated by scripts/local-litellm.sh. Do not add a cloud upstream here:"
        echo "# the absence of one is what makes a misrouted request fail instead of bill."
        echo "model_list:"
        for m in "${CHAT_NAMES[@]}"; do
            printf '  - model_name: %s\n    litellm_params:\n      model: ollama_chat/%s\n      api_base: %s\n' \
                   "$m" "$CHAT" "$OLLAMA"
        done
        for m in "${EMBED_NAMES[@]}"; do
            printf '  - model_name: %s\n    litellm_params:\n      model: ollama/%s\n      api_base: %s\n' \
                   "$m" "$EMBED" "$OLLAMA"
        done
        echo "litellm_settings:"
        echo "  drop_params: true          # a local model rejects params a frontier one accepts"
        echo "  request_timeout: 600       # a 30B model on one GPU is not a hosted endpoint"
        echo "general_settings:"
        echo "  master_key: $KEY"
    } > "$CONF"
    echo "  wrote $CONF (${#CHAT_NAMES[@]} chat aliases -> $CHAT, ${#EMBED_NAMES[@]} embedding -> $EMBED)"
}

case "$1" in
    write) write_conf ;;
    models) printf '  %s\n' "${CHAT_NAMES[@]}" ;;
    up)
        write_conf
        docker rm -f "$NAME" >/dev/null 2>&1
        # host networking so the proxy reaches ollama on 127.0.0.1 and CRS
        # containers reach the proxy on the docker bridge gateway.
        docker run -d --name "$NAME" --network host \
            -v "$CONF:/app/config.yaml:ro" \
            ghcr.io/berriai/litellm:main-latest \
            --config /app/config.yaml --port "$PORT" >/dev/null || {
                echo "  failed to start; is ghcr.io/berriai/litellm pullable?" >&2; exit 1; }
        echo "  $NAME up on :$PORT"
        gw=$(ip -4 addr show docker0 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1)
        echo "  point the CRS at it:"
        echo "    export AIXCC_LITELLM_HOSTNAME=http://${gw:-172.17.0.1}:$PORT"
        echo "    export LITELLM_KEY='$KEY'"
        ;;
    down) docker rm -f "$NAME" >/dev/null 2>&1 && echo "  $NAME removed" ;;
    check)
        echo "  proxy:  $(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/health/liveliness" 2>/dev/null)"
        echo "  ollama: $(curl -s -o /dev/null -w '%{http_code}' "$OLLAMA/api/version" 2>/dev/null)"
        curl -s "http://127.0.0.1:$PORT/v1/chat/completions" \
             -H "Authorization: Bearer $KEY" -H 'content-type: application/json' \
             -d '{"model":"claude-4-sonnet","messages":[{"role":"user","content":"reply with: ok"}],"max_tokens":256}' \
        | python3 -c "
import json,sys
try:
    d=json.load(sys.stdin)
except Exception as e:
    print('  chat: no json'); raise SystemExit
if 'error' in d: print('  chat: ERROR', str(d['error'])[:90])
else: print('  chat:', repr(d['choices'][0]['message']['content'][:40]), '<- served by ollama, billed to nobody')
" ;;
    *) usage ;;
esac
